In [2]:
import numpy as np

In [9]:
data = np.genfromtxt("solar_system_census.csv",delimiter=',')

In [12]:
data=data[1:,1:]


In [13]:
data[:5]

array([[172.27415062,  86.9703492 ,   1.01809825],
       [198.97747923, 104.85555332,   0.69741434],
       [207.11968072,  87.40104689,   0.72336138],
       [184.64272105,  63.14229518,   0.54773871],
       [179.38481426,  67.52325676,   1.07602237]])

In [28]:
dist_matrix = np.zeros((data.shape[0], 3))

In [50]:
centroids=[[1,100,1],[50,200,1],[58,210,1]]

In [51]:
for i in range(3):
    dist_matrix[:, i] = np.linalg.norm(data - centroids[i], axis=1)

In [52]:
dist_matrix

array([[171.76905076, 166.51327334, 167.91330145],
       [198.03724457, 176.76777594, 175.86954221],
       [206.5045591 , 193.30078851, 193.04729734],
       [187.30548294, 191.9867137 , 193.92206888],
       [181.31708852, 185.1770057 , 187.17345238],
       [201.26794991, 190.6128009 , 190.73385894],
       [172.11686919, 167.92496165, 169.41377389],
       [191.73859048, 195.70922675, 197.48009597],
       [180.83793868, 172.57490055, 173.433475  ],
       [190.94304418, 176.79223028, 176.80402349],
       [190.32753866, 180.05244078, 180.46757454],
       [193.98537382, 179.23933499, 179.1146418 ],
       [187.69836702, 174.18080567, 174.34003174],
       [179.32466211, 179.38691107, 181.07715926],
       [197.25048179, 189.7960151 , 190.32890078],
       [181.33768983, 167.99443414, 168.34437027],
       [192.84087681, 185.47692972, 186.12009243],
       [187.43544431, 180.87053119, 181.72273389],
       [157.02606375, 145.87718879, 147.23065274],
       [194.19010084, 182.27676

In [54]:
cluster=np.argmin(dist_matrix, axis=1)

In [57]:
data0=data[cluster==0]

In [56]:
data[cluster==1]

array([[172.27415062,  86.9703492 ,   1.01809825],
       [201.67421669,  84.55237279,   0.86873354],
       [172.47154363,  85.11106319,   0.78565017],
       [181.45156018,  88.18505435,   0.96057855],
       [191.86364884,  94.50057924,   0.73533952],
       [190.94627687,  87.95977703,   0.86998543],
       [188.61838809,  94.53060942,   0.67875318],
       [197.26037936,  80.2635402 ,   0.70299316],
       [182.30324452,  96.47254944,   0.78006377],
       [192.98571313,  81.86156211,   0.70539104],
       [187.63022057,  82.64567558,   0.81566384],
       [158.01387945, 101.95335152,   0.89619359],
       [194.90156778,  89.41811779,   1.032327  ],
       [167.62270465,  95.98281844,   0.73242769],
       [184.75772431,  86.10127811,   0.78837487],
       [199.15593147,  88.4373548 ,   0.90157405],
       [182.1658859 ,  82.04290761,   1.08553098],
       [181.20065606,  79.11502292,   1.04784935],
       [183.17079322,  90.43983224,   0.8015824 ],
       [177.4503826 ,  81.10474

In [58]:
center = [np.mean(data0[:,0]),np.mean(data0[:,1]),np.mean(data0[:,2])]

In [59]:
center

[175.46170053613025, 70.58133751684157, 0.9091599204254129]